---
title: "My very first water protocol"
author:
  - name:
      given: "Hans"
      family: "Van Calster"
    email: "hans.vancalster@inbo.be"
    orcid: "0000-0001-8595-8426"
    affiliation: "Research Institute for Nature and Forest (INBO)"
    corresponding: true
reviewer:
  - name:
      given: "Els"
      family: "Lommelen"
    email: "els.lommelen@inbo.be"
    orcid: "0000-0002-3481-5684"
    affiliation: "Research Institute for Nature and Forest (INBO)"
file_manager:
  - name:
      given: "Hans"
      family: "Van Calster"
    email: "hans.vancalster@inbo.be"
    orcid: "0000-0001-8595-8426"
    affiliation: "Research Institute for Nature and Forest (INBO)"
keywords: "kw"
language: en
date: "`r Sys.Date()`"
protocol_code: sfp-102-en
version_number: "2025.01"
template_name: sfp
theme: water
community: "inbo"
publisher: Research Institute for Nature and Forest (INBO)
site: bookdown::bookdown_site
bibliography: references.yaml
link-citations: TRUE
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/research-institute-for-nature-and-forest.csl
doi: 10.5072/zenodo.199100
---

```{=html}
<!--
Instructions for drawing up the protocol:

Below you will find the different parts of a protocol.
In the accompanying separate `Rmd` files you will find a description of what must be mentioned with each part.
It is in those files that you need to edit.
Not all parts always apply.
In those cases, leave the title headings and explicitly state "not applicable".
-->
```
```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  out.width = "100%",
  warning = FALSE,
  error = TRUE,
  message = FALSE
)
library(dplyr)
library(purrr)
library(protocolhelper)
library(pander)
panderOptions("table.alignment.default", "left")
metadata <- rmarkdown::metadata
path_to_protocol <- get_path_to_protocol(metadata$protocol_code)
type <- get_protocol_type(metadata$protocol_code, auto_identifier = TRUE)
```

# Metadata {.unnumbered}

```{r metadata-table}
revs <- map_chr(
  metadata[["reviewer"]],
  \(x) x$name |> paste(collapse = " ")
)
fms <-  map_chr(
  metadata[["file_manager"]],
  \(x) x$name |> paste(collapse = " ")
)
tibble(
  reviewers = revs,
  `file manager` = fms,
  protocolcode = metadata[["protocol_code"]],
  `version number` = metadata[["version_number"]],
  language = metadata[["language"]],
  theme = metadata[["theme"]]
) %>%
  pander::pander(split.tables = Inf)
rm(revs, fms)
```

```{r results="asis"}
sprintf("Check the [table listing all versions](../%s.html){target=\"_blank\"} to see if a more recent version is available.", type) |> cat() # nolint
```
