---
title: How to work with GPS
subtitle: subtitle
author:
- name: Van Calster, Hans
  orcid: 0000-0001-8595-8426
date: '2023-01-09'
reviewers: someone else
file_manager: who?
protocol_code: sip-003-en
version_number: '2023.01'
language: en
template_name: generic
site: bookdown::bookdown_site
bibliography: references.yaml
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/research-institute-for-nature-and-forest.csl
url: https://inbo.github.io/protocols/
github_repo: inbo/protocolsource
---

```{=html}
<!--
Instructions for drawing up the protocol:

Below you will find the different parts of a protocol.
In the accompanying separate `Rmd` files you will find a description of what must be mentioned with each part.
It is in those files that you need to edit.
Not all parts always apply.
In those cases, leave the title headings and explicitly state "not applicable".
-->
```
```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  out.width = "100%",
  warning = FALSE,
  error = TRUE,
  message = FALSE
)
library(dplyr)
library(purrr)
library(protocolhelper)
path_to_protocol <- get_path_to_protocol(rmarkdown::metadata$protocol_code)
type <- get_protocol_type(rmarkdown::metadata$protocol_code,
                          auto_identifier = TRUE)
```

# Metadata {.unnumbered}

```{r metadata-table}
rmarkdown::metadata %>%
  as_tibble() %>%
  select(reviewers, file_manager, protocol_code, version_number, language) %>%
  kable()
```

```{r results="asis"}
sprintf("Check the [table listing all versions](../%s.html){target=\"_blank\"} to see if a more recent version is available.", type) |> cat() # nolint
```
