---
title: Gebruik van het LIMS
author:
- name: Van Calster, Hans
  orcid: 0000-0001-8595-8426
date: '2023-01-12'
reviewers: someone else
file_manager: who?
protocol_code: sop-030c-nl
version_number: '2023.02'
language: nl
template_name: generic
site: bookdown::bookdown_site
bibliography: referenties.yaml
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/research-institute-for-nature-and-forest.csl
url: https://inbo.github.io/protocols/
github_repo: inbo/protocolsource
---

```{=html}
<!--
Instructies bij opmaak van het protocol:

Hieronder vind je de verschillende onderdelen van een protocol.
In de bijhorende losse `Rmd` bestanden vind je een beschrijving wat er bij elk onderdeel vermeld moet worden.
Het is in die bestanden dat je moet editeren.
Niet alle onderdelen zijn altijd van toepassing.
Laat in die gevallen de titels staan en vermeld expliciet "niet van toepassing".
-->
```
```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  eval = TRUE,
  dpi = 300,
  fig.width = 150 / 25.4,
  fig.height = 100 / 25.4,
  out.width = "100%",
  warning = FALSE,
  error = TRUE,
  message = FALSE
)
library(dplyr)
library(purrr)
library(protocolhelper)
path_to_protocol <- get_path_to_protocol(rmarkdown::metadata$protocol_code)
type <- get_protocol_type(rmarkdown::metadata$protocol_code,
                          auto_identifier = TRUE)
```

# Metadata {.unnumbered}

```{r metadata-table}
rmarkdown::metadata %>%
  as_tibble() %>%
  select(reviewers,
         documentbeheerder = file_manager,
         protocolcode = protocol_code,
         versienummer = version_number,
         taal = language) %>%
  kable()
```

```{r results="asis"}
sprintf("Controleer [deze tabel](../%s.html){target=\"_blank\"} om te zien of een meer recente versie beschikbaar is.", type) |> cat() # nolint  
```
