name: auto-approve

on:
  workflow_run:
    workflows: ['After review jobs']
    types: [completed]

  approve:
    runs-on: ubuntu-latest
    # Only run this job if After review jobs succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "auto-approve after update-protocol"
    steps:
      - name: Auto-approve pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pullRequestNumber = context.payload.pull_request.number;
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullRequestNumber,
              event: 'APPROVE',
              body: 'Automatically approved after successful protocol update'
            });
