name: Get latest merged PR branch

on:
  push:
    branches:
     - main

jobs:
  get-merged-branch:
    runs-on: ubuntu-latest
    name: "add protocol to website"
    steps:
      - name: checkout the repository
        uses: actions/checkout@v4
      - name: Get branch names
        id: branch-names
        uses: tj-actions/branch-names@v8
      - name: current branch names
        run: |
          echo "${{ steps.branch-names.outputs.current_branch }}"
      - name: ref branch names
        run: |
          echo "${{ steps.branch-names.outputs.ref_branch }}"
      - name: head ref branch names
        run: |
          echo "${{ steps.branch-names.outputs.head_ref_branch }}"
      - name: Checkout repo and build website
        if: (startsWith(env.RECENT_MERGED_BRANCH_NAME, 'sfp-')
          || startsWith(env.RECENT_MERGED_BRANCH_NAME, 'sip-')
          || startsWith(env.RECENT_MERGED_BRANCH_NAME, 'sop-')
          || startsWith(env.RECENT_MERGED_BRANCH_NAME, 'sap-')
          || startsWith(env.RECENT_MERGED_BRANCH_NAME, 'spp-'))
        uses: inbo/actions/protocol_website@main
        with:
          PAT: ${{ secrets.PAT }}
          GITHUB_REPOSITORY_DEST: "inbo/protocols"
          RECENT_MERGED_BRANCH_NAME: $RECENT_MERGED_BRANCH_NAME
