name: Get latest merged PR branch

on:
  push:
    branches:
     - main

jobs:
  get-merged-branch:
    runs-on: ubuntu-latest
    name: "add protocol to website"
    steps:
      - name: checkout the repository
        uses: actions/checkout@v4
      - name: Get latest merged PR targeting main
        id: get-pr
        run: |
          $(git log --merges origin/main --oneline --grep='^Merge' -1)
          "$(git log --merges origin/main --oneline --grep='^Merge' -1 | grep -oe 'ElsLommelen/.*$')"
          echo "$(git log --merges origin/main --oneline --grep='^Merge' -1 | grep -oe 'ElsLommelen/.*$' | awk -F '/' '{print $2}')"
          $(git log --merges origin/main --oneline --grep='^Merge' -1 | grep -o 'ElsLommelen/.*$' | awk -F '/' '{print $2}')
          $(git log --merges origin/main --oneline --grep='^Merge' -1 | grep -o 'ElsLommelen/.*$' | awk -F '/' '{print $2}')
          echo "RECENT_MERGED_BRANCH_NAME=$(git log --merges origin/main --oneline --grep='^Merge' -1 | grep -oe 'ElsLommelen/.*$' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      - name: Use the value
        run: echo $RECENT_MERGED_BRANCH_NAME
      - name: old method
        run: echo ${{ env.RECENT_MERGED_BRANCH_NAME }}
      - name: Checkout repo and build website
        if: (startsWith(env.RECENT_MERGED_BRANCH_NAME, 'sfp-')
          || startsWith(env.RECENT_MERGED_BRANCH_NAME, 'sip-')
          || startsWith(env.RECENT_MERGED_BRANCH_NAME, 'sop-')
          || startsWith(env.RECENT_MERGED_BRANCH_NAME, 'sap-')
          || startsWith(env.RECENT_MERGED_BRANCH_NAME, 'spp-'))
        uses: inbo/actions/protocol_website@main
        with:
          PAT: ${{ secrets.PAT }}
          GITHUB_REPOSITORY_DEST: "inbo/protocols"
          RECENT_MERGED_BRANCH_NAME: $RECENT_MERGED_BRANCH_NAME
