name: Get latest merged PR branch

on:
  push:
    branches:
     - main

jobs:
  get-merged-branch:
    runs-on: ubuntu-latest
    name: "add protocol to website"
    steps:
      - name: checkout the repository
        uses: actions/checkout@v4
      - name: Get latest merged PR targeting main
        id: get_pr
        run: |
          RECENT_MERGED_BRANCH_NAME=$(git log --merges origin/main --oneline --grep='^Merge' -1 | grep -oe 'ElsLommelen/.*$' | awk -F '/' '{print $2}')
      - name: Use the value
        run: echo "Recent merged branch name is: ${{ steps.get_pr.outputs.RECENT_MERGED_BRANCH_NAME}}"
      - name: Checkout repo and build website
        if: (startsWith(${{ steps.get_pr.outputs.RECENT_MERGED_BRANCH_NAME}}, 'sfp-')
          || startsWith(${{ steps.get_pr.outputs.RECENT_MERGED_BRANCH_NAME}}, 'sip-')
          || startsWith(${{ steps.get_pr.outputs.RECENT_MERGED_BRANCH_NAME}}, 'sop-')
          || startsWith(${{ steps.get_pr.outputs.RECENT_MERGED_BRANCH_NAME}}, 'sap-')
          || startsWith(${{ steps.get_pr.outputs.RECENT_MERGED_BRANCH_NAME}}, 'spp-'))
        uses: inbo/actions/protocol_website@main
        with:
          PAT: ${{ secrets.PAT }}
          GITHUB_REPOSITORY_DEST: "inbo/protocols"
          RECENT_MERGED_BRANCH_NAME: ${{ steps.get_pr.outputs.RECENT_MERGED_BRANCH_NAME}}
