name: Get latest merged PR branch

on:
  push:
    branches:
     - main

jobs:
  get-merged-branch:
    runs-on: ubuntu-latest
    name: "add protocol to website"
    steps:
      - name: checkout the repository
        uses: actions/checkout@v4
      - name: Get latest merged PR targeting main
        id: get-pr
        run: |
          merged_branch=$(git log --merges origin/main --oneline --grep='^Merge' -1 | grep -oe "ElsLommelen/.*$" | awk -F '/' '{print $2}')
          echo "merged_branch=$merged_branch" >> $RECENT_MERGED_BRANCH_NAME
      - name: Checkout repo and build website
        if: (startsWith(env.RECENT_MERGED_BRANCH_NAME, 'sfp-')
          || startsWith(env.RECENT_MERGED_BRANCH_NAME, 'sip-')
          || startsWith(env.RECENT_MERGED_BRANCH_NAME, 'sop-')
          || startsWith(env.RECENT_MERGED_BRANCH_NAME, 'sap-')
          || startsWith(env.RECENT_MERGED_BRANCH_NAME, 'spp-'))
        uses: inbo/actions/protocol_website@main
        with:
          PAT: ${{ secrets.PAT }}
          GITHUB_REPOSITORY_DEST: "inbo/protocols"
          RECENT_MERGED_BRANCH_NAME: $RECENT_MERGED_BRANCH_NAME
