name: On merge of "Log RECENT_MERGED_BRANCH_NAME" to main, build the protocol and add it to the website

on:
  push:
    branches:
     - main

jobs:
  build-website:
    runs-on: ubuntu-latest
    name: "add protocol to website"
    steps:
      - name: lookup branch name
        uses: actions/checkout@v2
      - uses: tonynguyenit18/github-action-custom-vars@v1
      - name: test
        run: echo 'branch name = ' $RECENT_MERGED_BRANCH_NAME
      - name: Checkout repo and build website
        uses: ElsLommelen/actions/protocol_website@protocols
        with:
          PAT: ${{ secrets.PAT }}
          GITHUB_REPOSITORY_DEST: "ElsLommelen/protocols"
          RECENT_MERGED_BRANCH_NAME: $RECENT_MERGED_BRANCH_NAME
        # if: ${{ startsWith(RECENT_MERGED_BRANCH_NAME, 'sfp-')
        #   || startsWith(RECENT_MERGED_BRANCH_NAME, 'sip-')
        #   || startsWith(RECENT_MERGED_BRANCH_NAME, 'sop-')
        #   || startsWith(RECENT_MERGED_BRANCH_NAME, 'sap-')
        #   || startsWith(RECENT_MERGED_BRANCH_NAME, 'spp-') }}
