name: Update repo NEWS and zenodo files on approval of pull request

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write  # This gives write permission to repository contents
  pull-requests: write  # Adding permission to approve pull requests

jobs:
  build:
    if: github.event.review.state == 'approved'
      && github.event.pull_request.base.ref == 'main'
      && (startsWith(github.event.pull_request.head.ref, 'sfp-')
      || startsWith(github.event.pull_request.head.ref, 'sip-')
      || startsWith(github.event.pull_request.head.ref, 'sop-')
      || startsWith(github.event.pull_request.head.ref, 'sap-')
      || startsWith(github.event.pull_request.head.ref, 'spp-'))
    runs-on: ubuntu-latest
    name: "update repo news, zenodo and protocol-specific doi"
    steps:
      - name: Update protocol
        uses: ElsLommelen/actions/protocol_update@protocols
        with:
          PAT: ${{ secrets.GITHUB_TOKEN }}
          ZENODO_SANDBOX: ${{ secrets.ZENODO_SANDBOX }}
          
      - name: Auto-approve pull request
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pullRequestNumber = context.payload.pull_request.number;
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullRequestNumber,
              event: 'APPROVE',
              body: 'Automatically approved after successful protocol update'
            });
